package com.zerlings.gabeisfaker.utils;

import android.content.Context;

import com.zerlings.gabeisfaker.MyApplication;
import com.zerlings.gabeisfaker.R;
import com.zerlings.gabeisfaker.db.Case;
import com.zerlings.gabeisfaker.db.Weapon;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by 令子 on 2017/2/14.
 */

public class InitUtils {

    public static List<Case> initCase(){

        List<Case> caseList = new ArrayList<>(27);

        Context context = MyApplication.getContext();

        Case clutchCase = new Case(context.getResources().getString(R.string.clutch_case),R.drawable.clutch_case);
        caseList.add(clutchCase);
        Case spectrum2Case = new Case(context.getResources().getString(R.string.spectrum_2_case),R.drawable.spectrum_2_case);
        caseList.add(spectrum2Case);
        Case operationHydraCase = new Case(context.getResources().getString(R.string.operation_hydra_case),R.drawable.operation_hydra_case);
        caseList.add(operationHydraCase);
        Case spectrumCase = new Case(context.getResources().getString(R.string.spectrum_case),R.drawable.spectrum_case);
        caseList.add(spectrumCase);
        Case gloveCase = new Case(context.getResources().getString(R.string.clutch_case),R.drawable.clutch_case);
        caseList.add(gloveCase);
        Case gamma2Case = new Case(context.getResources().getString(R.string.gamma_2_case),R.drawable.gamma_2_case);
        caseList.add(gamma2Case);
        Case gammaCase = new Case(context.getResources().getString(R.string.gamma_case),R.drawable.gamma_case);
        caseList.add(gammaCase);
        Case csgoWeaponCase = new Case(context.getResources().getString(R.string.csgo_weapon_case),R.drawable.csgo_weapon_case);
        caseList.add(csgoWeaponCase);
        Case csgoWeaponCase2 = new Case(context.getResources().getString(R.string.csgo_weapon_case_2),R.drawable.csgo_weapon_case_2);
        caseList.add(csgoWeaponCase2);
        Case csgoWeaponCase3 = new Case(context.getResources().getString(R.string.csgo_weapon_case_3),R.drawable.csgo_weapon_case_3);
        caseList.add(csgoWeaponCase3);
        Case chromaCase = new Case(context.getResources().getString(R.string.chroma_case),R.drawable.chroma_case);
        caseList.add(chromaCase);
        Case chromaCase2 = new Case(context.getResources().getString(R.string.chroma_case_2),R.drawable.chroma_2_case);
        caseList.add(chromaCase2);
        Case chromaCase3 = new Case(context.getResources().getString(R.string.chroma_case_3),R.drawable.chroma_3_case);
        caseList.add(chromaCase3);
        Case eSports2013Case = new Case(context.getResources().getString(R.string.esports_2013_case),R.drawable.esports_2013_case);
        caseList.add(eSports2013Case);
        Case eSports2013WinterCase = new Case(context.getResources().getString(R.string.esports_2013_winter_case),R.drawable.esports_2013_winter_case);
        caseList.add(eSports2013WinterCase);
        Case eSports2014SummerCase = new Case(context.getResources().getString(R.string.esports_2014_summer_case),R.drawable.esports_2014_summer_case);
        caseList.add(eSports2014SummerCase);
        Case falchionCase = new Case(context.getResources().getString(R.string.falchion_case),R.drawable.falchion_case);
        caseList.add(falchionCase);
        Case huntsmanWeaponCase = new Case(context.getResources().getString(R.string.huntsman_weapon_case),R.drawable.huntsman_weapon_case);
        caseList.add(huntsmanWeaponCase);
        Case operationBravoCase = new Case(context.getResources().getString(R.string.operation_bravo_case),R.drawable.operation_bravo_case);
        caseList.add(operationBravoCase);
        Case operationBreakoutWeaponCase = new Case(context.getResources().getString(R.string.operation_breakout_weapon_case),R.drawable.operation_breakout_case);
        caseList.add(operationBreakoutWeaponCase);
        Case operationPhoenixCase = new Case(context.getResources().getString(R.string.operation_phoenix_weapon_case),R.drawable.operation_phoenix_weapon_case);
        caseList.add(operationPhoenixCase);
        Case operationVanguardCase = new Case(context.getResources().getString(R.string.operation_vanguard_weapon_case),R.drawable.operation_vanguard_weapon_case);
        caseList.add(operationVanguardCase);
        Case operationWildfireCase = new Case(context.getResources().getString(R.string.operation_wildfire_case),R.drawable.operation_wildfire_case);
        caseList.add(operationWildfireCase);
        Case revolverCase = new Case(context.getResources().getString(R.string.revolver_case),R.drawable.revolver_case);
        caseList.add(revolverCase);
        Case shadowCase = new Case(context.getResources().getString(R.string.shadow_case),R.drawable.shadow_case);
        caseList.add(shadowCase);
        Case winterOffensiveWeaponCase = new Case(context.getResources().getString(R.string.winter_offensive_weapon_case),R.drawable.winter_offensive_weapon_case);
        caseList.add(winterOffensiveWeaponCase);

        return caseList;
    }

    public static List<Weapon> initWeapon(int caseImgId){

        List<Weapon> weaponList = new ArrayList<>(18);

        Context context = MyApplication.getContext();
        
        Weapon weapon;

        switch (caseImgId){
            case R.drawable.clutch_case:
                weapon = new Weapon("MP9",context.getResources().getString(R.string.black_sand),R.drawable.mp9_black_sand,3,0,100,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.aloha),R.drawable.sg_553_aloha,3,0,55,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.oxide_blaze),R.drawable.xm1014_oxide_blaze,3,0,70,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.urban_hazard),R.drawable.p2000_urban_hazard,3,0,100,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.flame_test),R.drawable.fiven_seven_flame_test,3,0,65,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.night_riot),R.drawable.pp_bizon_night_riot,3,0,80,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("R8 Revolver",context.getResources().getString(R.string.grip),R.drawable.r8_revolver_grip,3,0,100,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("Negev",context.getResources().getString(R.string.lionfish),R.drawable.negev_lionfish,4,0,55,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.wild_six),R.drawable.nova_wild_six,4,0,80,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.swag_7),R.drawable.mag_7_swag_7,4,0,92,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.arctic_wolf),R.drawable.ump_45_arctic_wolf,4,0,80,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.sonar),R.drawable.glock_18_moonrise,4,0,65,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.stymphalian),R.drawable.aug_stymphalian,5,0,63,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.cortex),R.drawable.usp_s_cortex,5,0,100,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.mortis),R.drawable.awp_mortis,5,0,64,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.bloodsport),R.drawable.mp7_bloodsport,6,0,65,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.neo_noir),R.drawable.m4a4_neo_noir,6,0,90,R.drawable.clutch_case);
                weaponList.add(weapon);
                break;

            case R.drawable.spectrum_2_case:
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.the_empress),R.drawable.ak_47_the_empress,6,0,100,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.see_ya_later),R.drawable.p250_see_ya_later,6,0,70,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.leaded_glass),R.drawable.m4a1_s_leaded_glass,5,0,70,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.high_roller),R.drawable.pp_bizon_high_roller,5,0,100,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("R8 Revolver",context.getResources().getString(R.string.llama_cannon),R.drawable.r8_revolver_llama_cannon,5,3,70,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.tacticat),R.drawable.cz75_auto_tacticat,4,0,70,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.exposure),R.drawable.ump_45_exposure,4,0,55,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.phantom),R.drawable.sg_553_phantom,4,0,60,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.goo),R.drawable.mp9_goo,4,0,60,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.ziggy),R.drawable.xm1014_ziggy,4,0,72,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.off_world),R.drawable.glock_18_off_world,3,0,100,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.triqua),R.drawable.aug_triqua,3,0,100,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.hunter),R.drawable.g3sg1_hunter,3,0,100,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.cracked_opal),R.drawable.tec_9_cracked_opal,3,0,100,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.oceanic),R.drawable.mac_10_oceanic,3,0,60,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.morris),R.drawable.sawed_off_morris,3,0,100,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Jungle Slipstream",context.getResources().getString(R.string.jungle_slipstream),R.drawable.scar_20_jungle_slipstream,3,0,50,R.drawable.spectrum_2_case);
                weaponList.add(weapon);
                break;

            case R.drawable.operation_hydra_case:
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.hyper_beast),R.drawable.five_seven_hyper_beast,6,0,100,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.oni_taiji),R.drawable.awp_oni_taiji,6,0,50,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.sugar_rush),R.drawable.galil_ar_sugar_rush,5,0,55,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.hellfire),R.drawable.m4a4_hellfire,5,0,50,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.cobra_strike),R.drawable.dual_berettas_cobra_strike,5,0,60,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.deaths_head),R.drawable.ssg_08_deaths_head,4,0,51,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.woodsman),R.drawable.p2000_woodsman,4,0,80,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.death_grip),R.drawable.p90_death_grip,4,0,100,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.orbit_mk01),R.drawable.ak_47_orbit_mk01,4,0,55,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.red_rock),R.drawable.p250_red_rock,4,0,100,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.blueprint),R.drawable.scar_20_blueprint,3,0,86,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.aloha),R.drawable.mac_10_aloha,3,0,65,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.cut_out),R.drawable.tec_9_cut_out,3,0,100,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.macabre),R.drawable.famas_macabre,3,0,60,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.metal_flowers),R.drawable.ump_45_metal_flowers,3,0,70,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.hard_water),R.drawable.mag_7_hard_water,3,0,45,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.briefing),R.drawable.m4a1_s_briefing,3,0,80,R.drawable.operation_hydra_case);
                weaponList.add(weapon);
                break;
                
            case R.drawable.spectrum_case:
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.neo_noir),R.drawable.usp_s_neo_noir,6,0,70,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.bloodsport),R.drawable.ak_47_bloodsport,6,0,45,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.decimator),R.drawable.m4a1_s_decimator,5,0,85,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.xiangliu),R.drawable.cz75_auto_xiangliu,5,0,56,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.fever_dream),R.drawable.awp_fever_dream,5,0,55,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.seasons),R.drawable.xm1014_seasons,4,0,50,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.scaffold),R.drawable.ump_45_scaffold,4,0,100,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.last_dive),R.drawable.mac_10_last_dive,4,0,52,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("M249",context.getResources().getString(R.string.emerald_poison_dart),R.drawable.m249_emerald_poison_dart,4,0,45,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.crimson_tsunami),R.drawable.galil_ar_crimson_tsunami,4,0,55,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.zander),R.drawable.sawed_off_zander,3,5,100,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.ripple),R.drawable.p250_ripple,3,0,50,R.drawable.spectrum_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.akoben),R.drawable.mp7_akoben,3,0,70,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.capillary),R.drawable.five_seven_capillary,3,0,70,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.oxide_blaze),R.drawable.desert_eagle_oxide_blaze,3,0,50,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.blueprint),R.drawable.scar_20_blueprint,3,0,75,R.drawable.clutch_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.jungle_slipstream),R.drawable.pp_bizon_jungle_slipstream,3,0,50,R.drawable.clutch_case);
                weaponList.add(weapon);
                break;

            case R.drawable.glove_case:
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.buzz_kill),R.drawable.m4a4_buzz_kill,6,0,70,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.dragonfire),R.drawable.ssg_08_dragonfire,6,0,50,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.wasteland_princess),R.drawable.sawed_off_wasteland_princess,5,0,70,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.mecha_industries),R.drawable.famas_mecha_industries,5,0,50,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.shallow_grave),R.drawable.p90_shallow_grave,5,0,75,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.gila),R.drawable.nova_gila,4,0,30,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.flash_back),R.drawable.m4a1_s_flash_back,4,0,100,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.royal_consorts),R.drawable.dual_berettas_royal_consorts,4,0,100,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.stinger),R.drawable.g3sg1_stinger,4,0,70,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.cyrex),R.drawable.usp_s_cyrex,4,0,55,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("Gali AR",context.getResources().getString(R.string.black_sand),R.drawable.gali_ar_black_sand,3,0,100,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.sonar),R.drawable.mag_7_sonar,3,0,45,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.sand_scale),R.drawable.mp9_sand_scale,3,0,45,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.turf),R.drawable.p2000_turf,3,0,100,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.cirrus),R.drawable.mp7_cirrus,3,0,75,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.ironwork),R.drawable.glock_18_ironwork,3,0,100,R.drawable.glove_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.polymer),R.drawable.cz75_auto_polymer,3,0,50,R.drawable.glove_case);
                weaponList.add(weapon);
                break;

            case R.drawable.gamma_2_case:
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.neon_revolution),R.drawable.ak_47_neon_revolution,6,0,80,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.roll_cage),R.drawable.famas_roll_cage,6,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.fuel_injector),R.drawable.tec_9_fuel_injector,5,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.syd_mead),R.drawable.aug_syd_mead,5,0,80,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.airlock),R.drawable.mp9_airlock,5,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.petroglyph),R.drawable.mag_7_petroglyph,4,0,44,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.directive),R.drawable.desert_eagle_diretive,4,6,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.powercore),R.drawable.scar_20_powercore,4,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.triarch),R.drawable.sg_553_triarch,4,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.weasel),R.drawable.glock_18_weasel,4,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.imprint),R.drawable.cz75_auto_imprint,3,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.grim),R.drawable.p90_grim,3,0,80,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.ventilator),R.drawable.g3sg1_ventilator,3,0,45,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.briefing),R.drawable.ump_45_briefing,3,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.slipstream),R.drawable.xm1014_slipstream,3,0,50,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.scumbria),R.drawable.five_seven_scumbria,3,0,100,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Negev",context.getResources().getString(R.string.dazzle),R.drawable.negev_dazzle,3,10,65,R.drawable.gamma_2_case);
                weaponList.add(weapon);
                break;

            case R.drawable.gamma_case:
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.mecha_industries),R.drawable.m4a1_s_mecha_industries,6,0,80,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.wasteland_rebel),R.drawable.glock_18_wasteland_rebel,6,0,54,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.desolate_space),R.drawable.m4a4_desolate_space,5,0,100,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.imperial_dragon),R.drawable.p2000_imperial_dragon,5,0,63,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.bloodsport),R.drawable.scar_20_bloodsport,5,0,45,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.aristocrat),R.drawable.aug_aristocrat,4,0,66,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.limelight),R.drawable.sawed_off_limelight,4,0,100,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.chopper),R.drawable.p90_chopper,4,0,60,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.phobos),R.drawable.awp_phobos,4,0,40,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("R8 Revolver",context.getResources().getString(R.string.reboot),R.drawable.r8_revolver_reboot,4,0,100,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.ice_cap),R.drawable.tec_9_ice_cap,3,0,50,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.carnivore),R.drawable.mac_10_carnivore,3,5,100,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.iron_clad),R.drawable.p250_iron_clad,3,5,80,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.violent_daimyo),R.drawable.five_seven_violent_daimyo,3,0,70,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.harvester),R.drawable.pp_bizon_harvester,3,0,100,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.exo),R.drawable.nova_exo,3,0,50,R.drawable.gamma_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.aerial),R.drawable.sg_553_aerial,3,0,60,R.drawable.gamma_case);
                weaponList.add(weapon);
                break;

            case R.drawable.csgo_weapon_case:
                weapon = new Weapon("AWP",context.getResources().getString(R.string.lightning_strike),R.drawable.awp_lightning_strike,6,0,8,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.hypnotic),R.drawable.desert_eagle_hypnotic,5,0,8,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.case_hardened),R.drawable.ak_47_case_hardened,5,0,100,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.dark_water),R.drawable.m4a1_s_dark_water,4,10,26,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.dragon_tattoo),R.drawable.glock_18_dragon_tattoo,4,0,8,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.dark_water),R.drawable.usp_s_dark_water,4,10,26,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.skulls),R.drawable.mp7_skulls,3,10,26,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.ultraviolet),R.drawable.sg_553_ultraviolet,3,6,80,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.wings),R.drawable.aug_wings,3,0,14,R.drawable.csgo_weapon_case);
                weaponList.add(weapon);
                break;

            case R.drawable.csgo_weapon_case_2:
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.blood_in_the_water),R.drawable.ssg_08_blood_in_the_water,6,6,20,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.serum),R.drawable.usp_s_serum,5,0,25,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.cold_blooded),R.drawable.p90_cold_blooded,5,0,8,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.graphite),R.drawable.nova_graphite,4,0,12,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.hypnotic),R.drawable.mp9_hypnotic,4,0,8,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.hemoglobin),R.drawable.dual_berettas_hemoglobin,4,0,20,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.case_hardened),R.drawable.five_seven_case_hardened,4,0,100,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.hexane),R.drawable.famas_hexane,3,0,40,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.hive),R.drawable.p250_hive,3,0,30,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.crimson_web),R.drawable.scar_20_crimson_web,3,6,80,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.blood_tiger),R.drawable.m4a1_s_blood_tiger,3,0,30,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.blue_titanium),R.drawable.tec_9_blue_titanum,3,0,4,R.drawable.csgo_weapon_case_2);
                weaponList.add(weapon);
                break;

            case R.drawable.csgo_weapon_case_3:
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.victoria),R.drawable.cz75_auto_victoria,6,0,75,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.undertow),R.drawable.p250_undertow,5,0,20,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.the_fuschia_is_now),R.drawable.cz75_auto_the_fuschia_is_now,5,0,40,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.heirloom),R.drawable.desert_eagle_heirloom,4,0,80,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.tread_plate),R.drawable.cz75_auto_tread_plate,4,0,20,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.titanium_bit),R.drawable.tec_9_titanum_bit,4,0,20,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.copper_galaxy),R.drawable.five_seven_copper_galaxy,4,0,20,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.crimson_web),R.drawable.cz75_auto_crimson_web,3,6,80,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.stainless),R.drawable.usp_s_stainless,3,0,80,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.red_fragCam),R.drawable.p2000_red_fragcam,3,0,70,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.panther),R.drawable.dual_berettas_panther,3,0,58,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.blue_fissure),R.drawable.glock_18_blue_fissure,3,6,58,R.drawable.csgo_weapon_case_3);
                weaponList.add(weapon);
                break;

            case R.drawable.chroma_case:
                weapon = new Weapon("AWP",context.getResources().getString(R.string.man_o_war),R.drawable.awp_man_o_war,6,10,20,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.chatterbox),R.drawable.galil_ar_chatterbox,6,35,85,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.cartel),R.drawable.ak_47_cartel,5,0,75,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.dragon_king),R.drawable.m4a4_dragon_king,5,0,75,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.muertos),R.drawable.p250_muertos,5,0,60,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.malachite),R.drawable.mac_10_malachite,4,0,50,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.naga),R.drawable.desert_eagle_naga,4,0,100,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.serenity),R.drawable.sawed_off_serenity,4,0,50,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.urban_shock),R.drawable.dual_berettas_urban_shock,4,0,47,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.quicksilver),R.drawable.xm1014_quicksilver,3,0,50,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.deadly_poison),R.drawable.mp9_deadly_poison,3,0,100,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("M249",context.getResources().getString(R.string.system_lock),R.drawable.m249_system_lock,3,0,80,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.catacombs),R.drawable.glock_18_catacombs,3,0,50,R.drawable.chroma_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.grotto),R.drawable.scar_20_grotto,3,0,50,R.drawable.chroma_case);
                weaponList.add(weapon);
                break;

            case R.drawable.chroma_2_case:
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.neon_rider),R.drawable.mac_10_neon_rider,6,0,45,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.hyper_beast),R.drawable.m4a1_s_hyper_beast,6,0,100,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.djinn),R.drawable.famas_djinn,5,0,100,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.eco),R.drawable.galil_ar_eco,5,10,85,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.monkey_business),R.drawable.five_seven_monkey_business,5,10,90,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.worm_god),R.drawable.awp_worm_god,4,0,45,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.grand_prix),R.drawable.ump_45_grand_prix,4,25,39,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.heat),R.drawable.mag_7_heat,4,0,100,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.pole_position),R.drawable.cz75_auto_pole_position,4,0,70,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Negev",context.getResources().getString(R.string.man_o_war),R.drawable.negev_man_o_war,3,10,20,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.valence),R.drawable.p250_valence,3,0,80,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.origami),R.drawable.sawed_off_origami,3,0,55,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.armor_core),R.drawable.mp7_armor_core,3,0,50,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.bronze_deco),R.drawable.desert_eagle_bronze_deco,3,0,46,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.elite_build),R.drawable.ak_47_elite_build,3,0,100,R.drawable.chroma_2_case);
                weaponList.add(weapon);
                break;

            case R.drawable.chroma_3_case:
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.chanticos_fire),R.drawable.m4a1_s_chanticos_fire,6,0,99,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.judgement_of_anubis),R.drawable.pp_bizon_judgement_of_anubis,6,0,50,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.asiimov),R.drawable.p250_asiimov,5,10,100,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.fleet_flock),R.drawable.aug_fleet_flock,5,0,100,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.primal_saber),R.drawable.ump_45_primal_saber,5,0,77,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.firefight),R.drawable.galil_ar_firefight,4,0,100,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.black_tie),R.drawable.xm1014_black_tie,4,0,75,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.red_astor),R.drawable.cz75_auto_red_astor,4,0,100,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.ghost_crusader),R.drawable.ssg_08_ghost_crusader,4,0,100,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.re_entry),R.drawable.tec_9_re_entry,4,0,43,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.fubar),R.drawable.sawed_off_fubar,3,40,100,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.oceanic),R.drawable.p2000_oceanic,3,0,60,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.atlas),R.drawable.sg_553_atlas,3,0,81,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.bioleak),R.drawable.mp9_bioleak,3,0,50,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("M249",context.getResources().getString(R.string.spectre),R.drawable.m249_spectre,3,0,50,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.orange_crash),R.drawable.g3sg1_orange_crash,3,0,52,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.ventilators),R.drawable.dual_berettas_ventilators,3,0,45,R.drawable.chroma_3_case);
                weaponList.add(weapon);
                break;

            case R.drawable.esports_2013_case:
                weapon = new Weapon("P90",context.getResources().getString(R.string.death_by_kitty),R.drawable.p90_death_by_kitty,6,8,32,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.boom),R.drawable.awp_boom,5,6,28,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.red_laminate),R.drawable.ak_47_red_laminate,5,6,80,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.orange_ddpat),R.drawable.galil_ar_orange_ddpat,4,6,80,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.splash),R.drawable.p250_splash,4,6,18,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.orange_ddpat),R.drawable.sawed_off_orange_ddpat,4,6,80,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.memento),R.drawable.mag_7_memento,3,2,18,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.faded_zebra),R.drawable.m4a4_faded_zebra,3,6,80,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.doomkitty),R.drawable.famas_doomkitty,3,8,22,R.drawable.esports_2013_case);
                weaponList.add(weapon);
                break;

            case R.drawable.esports_2013_winter_case:
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.x_ray),R.drawable.m4a4_x_ray,6,0,30,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.afterimage),R.drawable.famas_afterimage,5,2,40,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.electric_hive),R.drawable.awp_electric_hive,5,0,40,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.cobalt_disruption),R.drawable.desert_eagle_cobalt_disruption,5,0,20,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.blue_laminate),R.drawable.ak_47_blue_laminate,4,2,40,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.blind_spot),R.drawable.p90_blind_spot,4,0,50,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.ghost_gamo),R.drawable.nova_ghost_camo,3,0,40,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.water_sigil),R.drawable.pp_bizon_water_sigil,3,0,50,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.blue_titanium),R.drawable.galil_ar_blue_titanium,3,0,4,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.nightshade),R.drawable.five_seven_nightshade,3,0,50,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.azure_zebra),R.drawable.g3sg1_azure_zebra,3,0,28,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.steel_disruption),R.drawable.p250_steel_disruption,3,0,20,R.drawable.esports_2013_winter_case);
                weaponList.add(weapon);
                break;

            case R.drawable.esports_2014_summer_case:
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.bullet_rain),R.drawable.m4a4_bullet_rain,6,2,46,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.jaguar),R.drawable.ak_47_jaguar,6,0,100,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.corticera),R.drawable.p2000_corticera,5,6,30,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.corticera),R.drawable.awp_corticera,5,6,30,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.bloomstick),R.drawable.nova_bloomstick,5,6,80,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.bengal_tiger),R.drawable.aug_bengal_tiger,5,6,80,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.steel_disruption),R.drawable.glock_18_steel_disruption,4,0,20,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.virus),R.drawable.p90_virus,4,6,80,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.ocean_foam),R.drawable.mp7_ocean_foam,4,0,8,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.crimson_web),R.drawable.desert_eagle_crimson_web,4,6,80,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.blue_streak),R.drawable.pp_bizon_blue_streak,4,6,80,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.hexane),R.drawable.cz75_auto_hexane,3,0,40,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.dark_water),R.drawable.ssg_08_dark_water,3,10,26,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.blood_tiger),R.drawable.usp_s_blood_tiger,3,0,30,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.red_python),R.drawable.xm1014_red_python,3,8,50,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.ultraviolet),R.drawable.mac_10_ultraviolet,3,6,80,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                weapon = new Weapon("Negev",context.getResources().getString(R.string.bratatat),R.drawable.negev_bratatat,3,0,100,R.drawable.esports_2014_summer_case);
                weaponList.add(weapon);
                break;

            case R.drawable.falchion_case:
                weapon = new Weapon("AWP",context.getResources().getString(R.string.hyper_beast),R.drawable.awp_hyper_beast,6,0,100,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.aquamarine_revenge),R.drawable.ak_47_aquamarine_revenge,6,0,100,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.cyrex),R.drawable.sg_553_cyrex,5,0,100,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.nemesis),R.drawable.mp7_nemesis,5,0,32,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.yellow_jacket),R.drawable.cz75_auto_yellow_jacket,5,0,100,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.neural_net),R.drawable.famas_neural_net,4,0,60,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.ruby_poison_dart),R.drawable.mp9_ruby_poison_dart,4,0,50,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("Negev",context.getResources().getString(R.string.loudmouth),R.drawable.negev_loudmouth,4,14,65,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.handgun),R.drawable.p2000_handgun,4,0,100,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.evil_daimyo),R.drawable.m4a4_evil_daimyo,4,0,52,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.rocket_pop),R.drawable.galil_ar_rocket_pop,3,0,100,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.riot),R.drawable.ump_45_riot,3,0,70,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.torque),R.drawable.usp_s_torque,3,0,46,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.bunsen_burner),R.drawable.glock_18_bunsen_burner,3,0,80,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.elite_build),R.drawable.ak_47_elite_build,3,0,100,R.drawable.falchion_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.ranger),R.drawable.nova_ranger,3,0,100,R.drawable.falchion_case);
                weaponList.add(weapon);
                break;

            case R.drawable.huntsman_weapon_case:
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.vulcan),R.drawable.ak_47_vulcan,6,0,90,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.desert_strike),R.drawable.m4a4_desert_strike,6,0,70,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.caiman),R.drawable.usp_s_caiman,5,0,40,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.orion),R.drawable.usp_s_orion,5,0,50,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.cyrex),R.drawable.scar_20_cyrex,5,0,50,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.atomic_alloy),R.drawable.m4a1_s_atomic_alloy,5,0,90,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.tatter),R.drawable.mac_10_tatter,4,0,50,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.heaven_guard),R.drawable.xm1014_heaven_guard,4,3,50,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.curse),R.drawable.mac_10_curse,4,0,50,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.torque),R.drawable.aug_torque,4,0,50,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.antique),R.drawable.pp_bizon_antique,4,0,50,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.module),R.drawable.p90_module,3,0,35,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.desert_warfare),R.drawable.p90_desert_warfare,3,0,50,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.retribution),R.drawable.dual_berettas_retribution,3,0,45,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.kami),R.drawable.galil_ar_kami,3,0,60,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.isaac),R.drawable.tec_9_isaac,3,0,100,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.slashed),R.drawable.ssg_08_slashed,3,15,80,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.poison_dart),R.drawable.cz75_auto_pole_position,3,0,70,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.twist),R.drawable.cz75_auto_twist,3,0,100,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.pulse),R.drawable.p2000_pulse,3,0,60,R.drawable.huntsman_weapon_case);
                weaponList.add(weapon);
                break;

            case R.drawable.operation_bravo_case:
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.golden_coil),R.drawable.desert_eagle_golden_koi,6,0,12,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.fire_serpent),R.drawable.ak_47_fire_serpent,6,6,76,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.ocean_foam),R.drawable.p2000_ocean_foam,5,0,12,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.emerald_dragon),R.drawable.p90_emerald_dragon,5,6,52,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.graphite),R.drawable.awp_graphite,5,0,12,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.graven),R.drawable.mac_10_graven,4,6,80,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.bright_water),R.drawable.m4a1_s_bright_water,4,10,22,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.zirka),R.drawable.m4a4_zirka,4,6,42,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.overgrowth),R.drawable.usp_s_overgrowth,4,6,80,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.bone_pile),R.drawable.ump_45_bone_pile,3,6,34,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.tempest),R.drawable.nova_tempest,3,6,22,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.wave_spray),R.drawable.sg_553_wave_spray,3,6,80,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.black_limba),R.drawable.dual_berettas_black_limba,3,6,80,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.shattered),R.drawable.galil_ar_shattered,3,6,80,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.demeter),R.drawable.g3sg1_demeter,3,6,80,R.drawable.operation_bravo_case);
                weaponList.add(weapon);
                break;

            case R.drawable.operation_breakout_case:
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.cyrex),R.drawable.m4a1_s_cyrex,6,0,50,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.asiimov),R.drawable.p90_asiimov,6,0,92,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.conspiracy),R.drawable.desert_eagle_conspiracy,5,0,30,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.water_elemental),R.drawable.glock_18_water_elemental,5,0,70,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.fowl_play),R.drawable.five_seven_fowl_play,5,0,100,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.osiris),R.drawable.pp_bizon_osiris,4,0,50,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.koi),R.drawable.nova_koi,4,0,30,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("CZ75-Auto",context.getResources().getString(R.string.tigris),R.drawable.cz75_auto_tigris,4,0,100,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.supernova),R.drawable.p250_supernova,4,0,40,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.ivory),R.drawable.p2000_ivory,3,0,100,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("Negev",context.getResources().getString(R.string.desert_strike),R.drawable.negev_desert_strike,3,0,50,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.abyss),R.drawable.ssg_08_abyss,3,0,100,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.urban_hazard),R.drawable.mp7_urban_hazard,3,0,50,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.labyrinth),R.drawable.ump_45_labyrinth,3,0,40,R.drawable.operation_breakout_case);
                weaponList.add(weapon);
                break;

            case R.drawable.operation_phoenix_weapon_case:
                weapon = new Weapon("AUG",context.getResources().getString(R.string.chameleon),R.drawable.aug_chameleon,6,0,50,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.asiimov),R.drawable.awp_asiimov,6,18,100,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.antique),R.drawable.nova_antique,5,0,30,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.trigon),R.drawable.p90_trigon,5,8,75,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.redline),R.drawable.ak_47_redline,5,10,70,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.pulse),R.drawable.sg_553_pulse,4,10,60,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.guardian),R.drawable.usp_s_guardian,4,0,38,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.sergeant),R.drawable.famas_sergeant,4,10,100,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.heat),R.drawable.mac_10_heat,4,0,100,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.heaven_guard),R.drawable.mag_7_heaven_guard,3,0,40,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Negev",context.getResources().getString(R.string.terrain),R.drawable.negev_terrain,3,0,45,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.corporal),R.drawable.ump_45_corporal,3,5,75,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.sandstorm),R.drawable.tec_9_sandstorm,3,10,70,R.drawable.operation_phoenix_weapon_case);
                weaponList.add(weapon);
                break;

            case R.drawable.operation_vanguard_weapon_case:
                weapon = new Weapon("P2000",context.getResources().getString(R.string.fire_elemental),R.drawable.p2000_fire_elemental,6,0,60,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.wasteland_rebel),R.drawable.ak_47_wasteland_rebel,6,5,70,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.cartel),R.drawable.p250_cartel,5,0,75,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.tranquility),R.drawable.xm1014__tranquility,5,0,50,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.cardiac),R.drawable.scar_20_cardiac,5,0,100,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.basilisk),R.drawable.m4a1_s_basilisk,4,0,68,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.grinder),R.drawable.glock_18_grinder,4,2,25,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.griffin),R.drawable.m4a4_griffin,4,0,80,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.highwayman),R.drawable.sawed_off_highwayman,4,0,100,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.murky),R.drawable.g3sg1_murky,3,0,25,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("UMP-45",context.getResources().getString(R.string.delusion),R.drawable.ump_45__delusion,3,6,35,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.dart),R.drawable.mp9_dart,3,0,46,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.firestarter),R.drawable.mag_7_firestarter,3,6,49,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.urban_hazard),R.drawable.five_seven_urban_hazard,3,0,25,R.drawable.operation_vanguard_weapon_case);
                weaponList.add(weapon);
                break;

            case R.drawable.operation_wildfire_case:
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.the_battlestar),R.drawable.m4a4_the_battlestar,6,0,64,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.fuel_injector),R.drawable.ak_47_fuel_injector,6,0,100,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.kumicho_dragon),R.drawable.desert_eagle_kumicho_dragon,5,0,76,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.elite_build),R.drawable.awp_elite_build,5,0,100,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.hyper_beast),R.drawable.nova_hyper_beast,5,0,60,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.praetorian),R.drawable.mag_7_praetorian,4,0,45,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.royal_legion),R.drawable.glock_18_royal_legion,4,0,100,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.valence),R.drawable.famas_valence,4,0,80,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.triumvirate),R.drawable.five_seven_triumvirate,4,0,61,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.imperial),R.drawable.mp7_impire,4,0,40,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.jambiya),R.drawable.tec_9_jambiya,3,0,100,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.lead_conduit),R.drawable.usp_s_lead_conduit,3,0,100,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.lapis_gator),R.drawable.mac_10_lapis_gator,3,0,50,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.photic_zone),R.drawable.pp_bizon_photic_zone,3,0,100,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.cartel),R.drawable.dual_berettas_cartel,3,0,100,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.necropos),R.drawable.ssg_08_necropos,3,0,100,R.drawable.operation_wildfire_case);
                weaponList.add(weapon);
                break;

            case R.drawable.revolver_case:
                weapon = new Weapon("R8 Revolver",context.getResources().getString(R.string.fade),R.drawable.r8_revolver_fade,6,0,40,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.royal_paladin),R.drawable.m4a4_royal_paladin,6,0,80,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.point_disarray),R.drawable.ak_47_point_disarray,5,0,67,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("P90",context.getResources().getString(R.string.shapewood),R.drawable.p90_shapewood,5,0,100,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.the_executioner),R.drawable.g3sg1_the_executioner,5,14,85,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.retrobution),R.drawable.five_seven_retrobution,4,0,100,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("Tec-9",context.getResources().getString(R.string.avalanche),R.drawable.tec_9_avalanche,4,0,100,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("SG 553",context.getResources().getString(R.string.tiger_moth),R.drawable.sg_553_tiger_moth,4,0,100,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.teclu_burner),R.drawable.xm1014_teclu_burner,4,0,65,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("PP-Bizon",context.getResources().getString(R.string.fuel_rod),R.drawable.pp_bizon_fuel_rod,4,0,100,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("Negev",context.getResources().getString(R.string.power_loader),R.drawable.negev_power_loader,4,0,100,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("AUG",context.getResources().getString(R.string.ricochet),R.drawable.aug_ricochet,3,0,80,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("P2000",context.getResources().getString(R.string.imperial),R.drawable.p2000_imperial,3,0,20,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("R8 Revolver",context.getResources().getString(R.string.crimson_web),R.drawable.r8_revolver_crimson_web,3,6,80,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.yorick),R.drawable.sawed_off_yorick,3,0,100,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.outbreak),R.drawable.scar_20_outbreak,3,0,50,R.drawable.revolver_case);
                weaponList.add(weapon);
                weapon = new Weapon("Desert Eagle",context.getResources().getString(R.string.corinthian),R.drawable.desert_eagle_corinthian,3,0,44,R.drawable.revolver_case);
                weaponList.add(weapon);
                break;

            case R.drawable.shadow_case:
                weapon = new Weapon("USP-S",context.getResources().getString(R.string.kill_confirmed),R.drawable.usp_s_kill_confirmed,6,0,100,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.golden_coil),R.drawable.m4a1_s_golden_coil,6,0,100,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("G3SG1",context.getResources().getString(R.string.flux),R.drawable.g3sg1_flux,5,0,90,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("AK-47",context.getResources().getString(R.string.frontside_misty),R.drawable.ak_47_frontside_misty,5,2,87,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("SSG 08",context.getResources().getString(R.string.big_iron),R.drawable.ssg_08_big_iron,5,0,64,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP7",context.getResources().getString(R.string.special_delivery),R.drawable.mp7_special_delivery,4,0,62,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.stone_cold),R.drawable.galil_ar_stone_cold,4,0,90,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("M249",context.getResources().getString(R.string.nebula_crusader),R.drawable.m249_nebula_crusader,4,0,100,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.wingshot),R.drawable.p250_wingshot,4,0,90,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.survivor_z),R.drawable.famas_survivor_z,3,0,60,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.green_marine),R.drawable.scar_20_green_marine,3,0,80,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("Glock-18",context.getResources().getString(R.string.wraiths),R.drawable.glock_18_wraiths,3,0,80,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAG-7",context.getResources().getString(R.string.cobalt_core),R.drawable.mag_7_cobalt_core,3,0,50,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.dualing_dragons),R.drawable.dual_berettas_dualing_dragons,3,0,100,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("MAC-10",context.getResources().getString(R.string.rangeen),R.drawable.mac_10_rangeen,3,0,50,R.drawable.shadow_case);
                weaponList.add(weapon);
                weapon = new Weapon("XM1014",context.getResources().getString(R.string.scumbria),R.drawable.xm1014_scumbria,3,0,100,R.drawable.shadow_case);
                weaponList.add(weapon);
                break;

            case R.drawable.winter_offensive_weapon_case:
                weapon = new Weapon("M4A4",context.getResources().getString(R.string.asiimov),R.drawable.m4a4_asiimov,6,18,100,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Sawed-Off",context.getResources().getString(R.string.the_kraken),R.drawable.sawed_off_the_kraken,6,0,40,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("M4A1-S",context.getResources().getString(R.string.guardian),R.drawable.m4a1_s_guardian,5,0,50,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("P250",context.getResources().getString(R.string.mehndi),R.drawable.p250_mehndi,5,0,100,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("AWP",context.getResources().getString(R.string.redline),R.drawable.awp_redline,5,10,40,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Nova",context.getResources().getString(R.string.rising_skull),R.drawable.nova_rising_skull,4,0,50,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("MP9",context.getResources().getString(R.string.rose_iron),R.drawable.mp9_rose_iron,4,0,30,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("FAMAS",context.getResources().getString(R.string.pulse),R.drawable.famas_pulse,4,0,40,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Dual Berettas",context.getResources().getString(R.string.marina),R.drawable.dual_berettas_marina,4,5,50,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Five-SeveN",context.getResources().getString(R.string.kami),R.drawable.five_seven_kami,3,0,30,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("SCAR-20",context.getResources().getString(R.string.magma),R.drawable.m249_magma,3,0,70,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("M249",context.getResources().getString(R.string.sandstorm),R.drawable.galil_ar_sandstorm,3,10,60,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);
                weapon = new Weapon("Galil AR",context.getResources().getString(R.string.cobalt_halftone),R.drawable.pp_bizon_cobalt_halftone,3,5,45,R.drawable.winter_offensive_weapon_case);
                weaponList.add(weapon);

                break;

            default:break;
        }
        return weaponList;
    }
}
